### PR TITLE
Check for self.protocol before using self.protocol.operations

### PR DESCRIPTION
**Pull request by Zakjholt**

### CODE REVIEW

**Comment by maggiolo00** [comment]
Hi @Zakjholt 

thanks for the PR. In which case you have the `op === 'string'` and the `self.protocol` null/undefined?

**Comment by Zakjholt** [comment]
I was receiving an error on this line where protocol was undefined and I checked the source code. I fixed the error that caused it in my own system, but I've always thought it's safest not to use properties two dots deep without checking that the first dot exists.

**Comment by maggiolo00** [comment]
Hi @Zakjholt 

Are you able to log which is inside `op` when it happens?
how can i reproduce this issue locally?

`self.protocol` should be there. Otherwise it should throw an error that means that the handshake went wrong

**Comment by Zakjholt** [comment]
I don't know that I could replicate it at this point, as my system has already been adjusted, so the state wouldn't be the same. The error was just `Cannot read property 'operations' of null` with that line number listed. I can tell you that my system is using the Network Binary driver, and almost entirely just using db.query with strings. Somehow the self.protocol was null though 😄

**Comment by maggiolo00** [comment]
hi @Zakjholt 

i imagine that this does not contain your patch. 

Which is the request that fails ? is it a query?

**Comment by Zakjholt** [comment]
It's a batch sql db.query with a `{ class: 's' }` config. The full query string is logged before the error

**Pull request closed without merging**
