### PR TITLE
Add some typeScript definitions  for orientjs .

### PR DESCRIPTION
**Pull request by saeedtabrizi**

### CODE REVIEW

**Comment by Talento90** [comment]
Hi @saeedtabrizi,  this PR is very useful. I'm going to use OrientDb and TypeScript together and I was looking for the definitions.

Could you please make a PR with your definitions for the [ main definition repository](https://github.com/DefinitelyTyped/DefinitelyTyped)?

Thanks :+1:

**Comment by saeedtabrizi** [comment]
Hi @Talento90  
yes , i updated some of  definitions now , i will commit and create PR asap . 

Regards
Saeed Tabrizi

**Comment by saeedtabrizi** [comment]
Hi @Talento90  
I create a PR now . #175 .

Regards 
Saeed Tabrizi

**Comment by maggiolo00** [comment]
@saeedtabrizi 

is this still valid?

**Comment by saeedtabrizi** [comment]
@maggiolo00 ,  the short answer is NO .
this definition must be change to support latest feature of orientjs certainly .
I'm working about it asap .

**Comment by maggiolo00** [comment]
@saeedtabrizi 

thanks

**Pull request closed without merging**
