### PR TITLE
Add  some feautres discussed in issue #232

### PR DESCRIPTION
**Pull request by saeedtabrizi**
Add some features that we discussed in https://github.com/orientechnologies/orientjs/issues/232

- Add vscode to .gitignore .
- Add support `engine` to index .
- Add` IF NOT EXIST` to create class and property . https://github.com/orientechnologies/orientdb/issues/3597
- Add `IF  EXIST` to drop class and property . https://github.com/orientechnologies/orientdb/issues/3597
- Add Some Sql Function methods like the `sequence` , `avg` , `abs` .
- Add Sequence `create , list , get , drop , alter `to Db .
- Add some use strict to resolve js hints .
- Upgrade Typescript definiton file (**orientjs.d.ts**) and correct the name of typescript . (also i add the definition file to  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14425#issuecomment-277273900) 

- All modification passed the test exactly on my computer. 

I hope to enjoy the new features and say a **Salavat bar Mohammad** now .

### CODE REVIEW

**Comment by maggiolo00** [comment]
Thanks @saeedtabrizi

**Comment by saeedtabrizi** [comment]
@maggiolo00  , I'm so happy if you assign the typescript or related feature bug reports or enhancement issues to me .  i will resolve them as soon as possible .

**Comment by saeedtabrizi** [comment]
@maggiolo00 please merge #235 fixtures too .  i put some newer fixures in this pull request .

**Comment by maggiolo00** [comment]
@saeedtabrizi 

sure i'm working on it now

**Pull request merged**
