### PR TITLE
Added default value as property

### PR DESCRIPTION
**Pull request by matanshukry**

### CODE REVIEW

**Comment by maggiolo00** [comment]
+1

I will add a test case for this

**Comment by maggiolo00** [comment]
I've added a test case for this on branch 2.1.x

https://github.com/orientechnologies/orientjs/commit/8fb76e4fcfa166efadbfff095708a3a147835428#diff-c4bc5cc4dd43749b388fa5fb27257ad7R54

Thanks
@matanshukry

**Comment by seeden** [comment]
This is not a good solution because

```js
0 || '' => ''
false || '' => ''
null || '' => ''
```

the good implementation of this is behaviour is:

```js
typeof config.defaultValue !== 'undefined' ? config.defaultValue : '';
```

**Comment by matanshukry** [comment]
Agreed, changed and created another PR ( #143 )

**Pull request merged**
