### PR TITLE
RawExpression in statements added .

### PR DESCRIPTION
**Pull request by saeedtabrizi**
to support RawExpression and orientdb functions in insert or update statements we can use db.rawExpression("'any value goes here '")

### CODE REVIEW

**Comment by saeedtabrizi** [comment]
this PR contains a set of commits to handle https://github.com/orientechnologies/orientjs/issues/189 issue .

**Comment by maggiolo00** [comment]
hi @saeedtabrizi 

i will merge also the typescript definition?

**Comment by saeedtabrizi** [comment]
hi @mamobyz 
Absolutely yes . this is the latest definition for orientjs .

Thanks

Saeed Tabrizi.

**Comment by maggiolo00** [comment]
Thanks @saeedtabrizi

**Pull request merged**
