### PR TITLE
Add in operator for where clause (fixes #145)

### LINKED ISSUE #145: Feature request: IN comparison operator
Currently there's no `in` operator to be used through the query builder. A nice implementation could be the following:

```javascript
db.select().from('OUser').in({ '@rid': userIds }).all()
```

### PR DESCRIPTION
**Pull request by dan-santana**
Just another where operator to handle the following statement:

```javascript
db.select().from('OUser').in({ '@rid': userIds }).all()
```

### CODE REVIEW

**Comment by maggiolo00** [comment]
hi @dan-santana 

can you sign the CLA then i will merge your pull request

**Comment by dan-santana** [comment]
I already signed it :)

**Comment by dan-santana** [comment]
I guess there was some problem when I signed the CLA, and if I try to sign it now I get the following:
2016-02-10-161025_2048x1152_scrot
Weird.

**Comment by maggiolo00** [comment]
@dan-santana  no problem

Thanks for this PR

**Pull request merged**
