### PR TITLE
allow optional resolver in db.query and record.get

### PR DESCRIPTION
**Pull request by jpstrikesback**
Re: #254 #219 

Instead of messing with orientjs internals I think allowing an optional resolver in userspace is a nicer 'option'

### CODE REVIEW

**Comment by jpstrikesback** [comment]
This of course needs docs, and more, but I've pushed this for an initial review.

Cheers!
JP

**Comment by maggiolo00** [comment]
Hi @jpstrikesback 

Thanks for the PR. I will review it ASAP. 
Sorry for the late response for on those issue. 

Thanks

**Comment by jpstrikesback** [comment]
Cheers @maggiolo00,

Fixed the lint errors and added an options default object.

This allows one to choose what to do with the results & prefetched, make their own response format, whatnot.

Seems like a win...

As long as this doesn't replace a working resolveReferences default with the ability to respect the fetchPlan, this seems good to have as well, as now I can make a normalized response according to whatever arbitrary format I need and choose where and when to place prefetched entities.

JP

**Comment by maggiolo00** [comment]
Thanks @jpstrikesback 

Yes this looks fine. 
All tests are green

Thanks for this PR

**Comment by jpstrikesback** [comment]
Thank you!

**Pull request merged**
